Get rid of some linting errors/warnings
Vyxal/Jyxal pull request #2
Opened 2022-03-04 23:38 UTC by cgccuser

A couple resources weren't closed, and a couple interfaces were redundantly implemented. That's about it.

2022-03-04 23:41 UTC, Lyxal approved these changes
Lgtm

2022-03-04 23:44 UTC, Seggan requested changes
I'm feeling quite picky today 😉

2022-03-04 23:44 UTC, Seggan commented on src/main/java/io/github/seggan/jyxal/runtime/ProgramStack.java
> +public class ProgramStack extends ArrayDeque<Object> {
I like being explicit with these

2022-03-04 23:44 UTC, Seggan commented on src/main/java/io/github/seggan/jyxal/runtime/RuntimeHelpers.java
> +        var shell = jShell.get();
Please don't use `var`

2022-03-04 23:44 UTC, Seggan commented on src/test/java/io/github/seggan/jyxal/TestHelper.java
> +            cl.close();
If you want it this way, put it in a `finally` block and remove both `close()` calls

2022-03-05 03:12 UTC, Seggan requested changes
I should've run refactor on the entire project lol

2022-03-05 03:12 UTC, Seggan commented on src/main/java/io/github/seggan/jyxal/runtime/math/internal/BigDecimalMath.java
> +import java.util.*;
No star imports please

2022-03-05 03:12 UTC, Seggan commented on src/main/java/io/github/seggan/jyxal/runtime/math/internal/BigDecimalMath.java
> +import static java.math.BigDecimal.*;
Same here

2022-03-05 03:12 UTC, Seggan commented on src/main/java/io/github/seggan/jyxal/runtime/math/internal/BigDecimalMath.java
> +					while (value > 1.4) { // never happens when called by logUsingExponent()
Spaces, not tabs

2022-03-23 15:00 UTC, closed without merging