Add factorial/sentence case element
Vyxal/Jyxal pull request #8
Opened 2022-05-07 00:52 UTC by Steffan153

I tried putting the code into Myxal, but it didn't work, so you can paste it in once Myxal works.

```
Parsing program...
Compiling program...
Extracting runtime classes...
Writing to jar...
Performing post-compilation optimisations...
ProGuard, version undefined
Unexpected error while computing stack sizes:
  Class       = [jyxal/Main]
  Method      = [main([Ljava/lang/String;)V]
  Exception   = [java.lang.IllegalArgumentException] (Stack size becomes negative after instruction [20] invokestatic #39 = Methodref(io/github/seggan/myxal/runtime/RuntimeMethods.factorial(Lio/github/seggan/myxal/runtime/ProgramStack;)Ljava/lang/Object;) in [jyxal/Main.main([Ljava/lang/String;)V])
Unexpected error while editing code:
  Class       = [jyxal/Main]
  Method      = [main([Ljava/lang/String;)V]
  Exception   = [java.lang.IllegalArgumentException] (Stack size becomes negative after instruction [20] invokestatic #39 = Methodref(io/github/seggan/myxal/runtime/RuntimeMethods.factorial(Lio/github/seggan/myxal/runtime/ProgramStack;)Ljava/lang/Object;) in [jyxal/Main.main([Ljava/lang/String;)V])
Exception in thread "main" java.lang.IllegalArgumentException: Stack size becomes negative after instruction [20] invokestatic #39 = Methodref(io/github/seggan/myxal/runtime/RuntimeMethods.factorial(Lio/github/seggan/myxal/runtime/ProgramStack;)Ljava/lang/Object;) in [jyxal/Main.main([Ljava/lang/String;)V]
        at proguard.classfile.attribute.visitor.StackSizeComputer.evaluateInstructionBlock(StackSizeComputer.java:348)
        at proguard.classfile.attribute.visitor.StackSizeComputer.visitCodeAttribute0(StackSizeComputer.java:162)
        at proguard.classfile.attribute.visitor.StackSizeComputer.visitCodeAttribute(StackSizeComputer.java:124)
        at proguard.classfile.editor.StackSizeUpdater.visitCodeAttribute(StackSizeUpdater.java:44)
        at proguard.classfile.editor.CodeAttributeEditor.visitCodeAttribute0(CodeAttributeEditor.java:595)
        at proguard.classfile.editor.CodeAttributeEditor.visitCodeAttribute(CodeAttributeEditor.java:530)
        at proguard.classfile.util.DynamicMemberReferenceInitializer.visitCodeAttribute(DynamicMemberReferenceInitializer.java:195)
        at proguard.classfile.attribute.CodeAttribute.accept(CodeAttribute.java:138)
        at proguard.classfile.ProgramMethod.attributesAccept(ProgramMethod.java:148)
        at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramMember(AllAttributeVisitor.java:94)
        at proguard.classfile.visitor.MemberVisitor.visitProgramMethod(MemberVisitor.java:57)
        at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:140)
        at proguard.classfile.ProgramClass.methodsAccept(ProgramClass.java:695)
        at proguard.classfile.visitor.AllMethodVisitor.visitAnyClass(AllMethodVisitor.java:46)
        at proguard.classfile.visitor.ClassVisitor.visitProgramClass(ClassVisitor.java:40)
        at proguard.classfile.ProgramClass.accept(ProgramClass.java:544)
        at proguard.classfile.ClassPool.classesAccept(ClassPool.java:291)
        at proguard.Initializer.execute(Initializer.java:228)
        at proguard.pass.PassRunner.run(PassRunner.java:24)
        at proguard.ProGuard.initialize(ProGuard.java:328)
        at proguard.ProGuard.execute(ProGuard.java:130)
        at io.github.seggan.myxal.app.Main.doMain(Main.kt:126)
        at io.github.seggan.myxal.app.Main.main(Main.kt:140)
```

2022-05-07 02:31 UTC, Seggan approved these changes
Yeah... sorry, but you could do a lot better

2022-05-07 02:31 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +fun factorial(stack: ProgramStack): Any {
The setup is weird, but for monads you simply take an `Any` as input. The element will automagically vectorise

2022-05-07 02:31 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        str.forEach {
I prefer explicit `for` loops

2022-05-07 02:31 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        JyxalList.range(BigComplex.ONE, a + 1).forEach {
Same here

2022-05-07 02:31 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        var ret = ""
`StringBuilder` exists for a reason

2022-05-07 02:32 UTC, Seggan requested changes, later dismissed
Woops hit wrong button

2022-05-07 02:32 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        JyxalList.range(BigComplex.ONE, a + 1).forEach {
Also the thing should be lazy, use `map` instead of `forEach`

2022-05-07 12:55 UTC, Seggan approved these changes
Much better. just some naming conventions

2022-05-07 12:55 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +fun decrement(a: Any): Any {
```suggestion
fun decrement(obj: Any): Any {
```

2022-05-07 12:55 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +fun factorial(a: Any): Any {
```suggestion
fun factorial(obj: Any): Any {
```

2022-05-07 12:55 UTC, Seggan submitted a review, later dismissed
Whats with me hitting the wrong buttons

2022-05-07 18:37 UTC, Steffan153 commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +}
```suggestion
    return if (obj is BigComplex) {
        obj - BigComplex.ONE
    } else {
        obj.toString() + "-"
    }
}
```

2022-05-07 18:38 UTC, Steffan153 commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +}
```suggestion
    return if (obj is BigComplex) {
        var res = BigComplex.ONE
        for (i in JyxalList.range(BigComplex.ONE, obj + 1)) {
            res *= i as BigComplex
        }
        res
    } else {
        val str = obj.toString()
        var capitalize = true
        var ret = StringBuilder()
        for (c in str) {
            if (capitalize) {
                ret.append(c.uppercaseChar())
            } else {
                ret.append(c.lowercaseChar())
            }
            if (capitalize && c != ' ') {
                capitalize = false
            }
            capitalize = capitalize || "!?.".contains(c)
        }
        ret.toString()
    }
}
```

2022-05-07 19:49 UTC, Seggan requested changes
Almost there

2022-05-07 19:49 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        is JyxalList -> {
yeah, once again, if you specify that monads are vectorised in `Element`, then the compiler will auto insert the vectorisation. Might want to remove this `is JyxalList`

2022-05-07 19:49 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        is JyxalList -> {
Same here

2022-05-07 20:00 UTC, cgccuser requested changes, later dismissed
Minor stuff

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        }
```suggestion
```

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        }
```suggestion
```

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    return if (obj is BigComplex) {
If you're going to use a single `return` and make the expression a big if statement, you might as well use `= ...` instead of `{ return .. }`. But I think it might look a bit nicer if you put the `return`s inside the `if` and `else`. It's a matter of personal style, though, feel free to resolve this comment.

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        for (i in JyxalList.range(BigComplex.ONE, obj + 1)) {
This would look prettier as a `fold`, I think

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        var ret = StringBuilder()
This can be a `val`

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        str.substring(str.length / 2)
```suggestion
        obj.toString().substring(str.length / 2)
```

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        str.substring(str.length / 2)
Honestly, I'd like this but I don't think Seggan likes that style
```kotlin
fun parity(obj: Any): Any =
    if (obj is BigComplex) obj % 2
    else obj.toString().substring(str.length / 2)
```

2022-05-07 20:00 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        }
```suggestion
        is BigComplex -> JyxalList.range(BigComplex.ONE, obj)
        else -> obj.toString().lowercase()
```
Or just make it an `if` statement

2022-05-07 20:02 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    return if (obj is BigComplex) {
I prefer returning instead of `=`

2022-05-07 20:03 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        var ret = StringBuilder()
Specifically, the `ret` variable

2022-05-07 20:03 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        str.substring(str.length / 2)
nope

2022-05-07 20:03 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    return if (obj is BigComplex) {
If we are using `return`, I think it'd look better if the `return`s were inside the if and else blocks

2022-05-07 20:04 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    return if (obj is BigComplex) {
Agree but the intellij complains lol

2022-05-07 20:08 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    return if (obj is BigComplex) {
Oh huh, this is fine then

2022-05-07 20:09 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        var ret = StringBuilder()
```suggestion
        val ret = StringBuilder()
```

2022-05-07 20:19 UTC, cgccuser commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +        res
```suggestion
        JyxalList
            .range(BigComplex.ONE, obj + 1)
            .fold(BigComplex.ONE){ acc, i -> acc * (i as BigComplex) }
```

2022-05-09 01:53 UTC, Seggan submitted a review, later dismissed

2022-05-09 01:53 UTC, Seggan commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> -        val str = obj.toString()
Now this does not compile. Keep the explicit variable.

2022-05-09 18:23 UTC, Steffan153 commented on src/main/kotlin/io/github/seggan/jyxal/runtime/RuntimeMethods.kt
> +    }
```suggestion
    } else {
        val str = obj.toString()
        str.substring(str.length / 2)
    }
```

2022-05-09 19:44 UTC, Seggan approved these changes

2022-05-09 23:18 UTC, merged